[[inputs.postgresql]]
	address   = "host=192.168.9.205 dbname=hosxp user=telegraf sslmode=disable"
	databases = ["hosxp"]

[[inputs.postgresql_extensible]]
	address   = "host=192.168.9.205 dbname=hosxp user=telegraf sslmode=disable"
	databases = ["hosxp"]

	[[inputs.postgresql_extensible.query]]
		sqlquery = "select count(1) as amount, state from pg_stat_activity where usename != 'telegraf' group by state"
		version  = 901
		withdbname = false
		tagvalue = "state"
		measurement = "pg_connections"

	[[inputs.postgresql_extensible.query]]
		sqlquery = "SELECT schema_name, pg_size_pretty(sum(table_size)::bigint) as disk_space, ((sum(table_size)::bigint) / 1024) / 1024 as size_MB FROM (SELECT pg_catalog.pg_namespace.nspname as schema_name, pg_relation_size(pg_catalog.pg_class.oid) as table_size FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON relnamespace = pg_catalog.pg_namespace.oid) t WHERE t.schema_name not in ('information_schema','pg_catalog','pg_toast') GROUP BY schema_name ORDER BY schema_name"
		version  = 901
		withdbname = false
		tagvalue = "schema_name"
		measurement = "pg_schemas_size"

	[[inputs.postgresql_extensible.query]]
		sqlquery = "select pg_xlog_location_diff(sent_location, write_location)::integer as write_lag, pg_xlog_location_diff(sent_location, flush_location)::integer as flush_lag, pg_xlog_location_diff(sent_location, replay_location)::integer as replay_lag from pg_stat_replication;"
		version  = 901
		withdbname = false
		tagvalue = ""
		measurement = "pg_stat_replication"

#########################################################################
## COLETANDO METRICAS DA REPLICAÇÃO NA BASE POSTGRES DO SERVIDOR SLAVE ##
#########################################################################

[[inputs.postgresql_extensible]]
	address   = "host=192.168.9.206 dbname=hosxp user=telegraf sslmode=disable"
	databases = ["hosxp"]

	[[inputs.postgresql_extensible.query]]
		sqlquery = "select case when pg_is_in_recovery() is true then 1 else 0 end as is_in_recovery;"
		version  = 901
		withdbname = false
		tagvalue = ""
		measurement = "pg_is_in_recovery"

	[[inputs.postgresql_extensible.query]]
		sqlquery = "SELECT CASE WHEN pg_last_xlog_receive_location() = pg_last_xlog_replay_location() THEN 0 ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp()) END AS log_delay;"
		version  = 901
		withdbname = false
		tagvalue = ""
		measurement = "pg_log_delay"